site_name: Flavio Regis de Arruda
markdown_extensions:
  - attr_list
plugins:
  - search
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  analytics:
    provider: google
    property: G-6DCR8Z4HKZ

